routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear',function(){
  \Artisan::call('config:cache');
return "ada";
});


Route::group(['middleware' => 'auth'],function() {
    Route::get('','DashboardController@index')->name('dashboard')->middleware('kaprodi.auth');

    Route::resource('user','UserController')->middleware('kaprodi.auth');

    Route::resource('fakultas','FakultasController',['parameters' => [
        'fakultas'  => 'fakultas'
    ]])->except(['show'])->middleware('kaprodi.auth');

    Route::resource('prodi','ProdiController')->except(['show'])->middleware('kaprodi.auth');

    Route::resource('kelas','KelasController',['parameters' => [
        'kelas' => 'kelas'
    ]])->except(['show'])->middleware('kaprodi.auth');

    Route::resource('matakuliah','MatakuliahController')->middleware('kaprodi.auth');
    Route::resource('tahun-ajaran','TahunAjaranController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('kurikulum','KurikulumController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('jenis-ujian','JenisUjianController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('jadwal-ujian','JadwalUjianController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('arsip-soal','ArsipSoalController')->except(['edit','update']);
    Route::resource('arsip-nilai','ArsipNilaiController')->except(['edit','update']);

    // export pdf
    Route::get('arsip-soal/pdf/{id}','ArsipSoalController@exportPdf')->name('arsip_soal.pdf');
    Route::get('arsip-nilai/pdf/{id}','ArsipNilaiController@exportPdf')->name('arsip_nilai.pdf');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/ArsipNilai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ArsipNilai extends Model
{
    protected $table = 'arsip_nilai';

    protected $fillable = [
        'id_user',
        'id_kurikulum',
        'id_jenis_ujian',
        'id_tahun_ajaran',
        'id_jadwal_ujian',
        'id_matakuliah',
        'id_fakultas',
        'id_prodi',
        'kode_nilai',
        'nilai'
    ];

    public function user()
    {
        return $this->belongsTo('App\User','id_user','id');
    }

    public function kurikulum()
    {
        return $this->belongsTo('App\Kurikulum','id_kurikulum','id');
    }

    public function jenisUjian()
    {
        return $this->belongsTo('App\JenisUjian','id_jenis_ujian','id');
    }

    public function tahunAjaran()
    {
        return $this->belongsTo('App\TahunAjaran','id_tahun_ajaran','id');
    }

    public function jadwalUjian()
    {
        return $this->belongsTo('App\JadwalUjian','id_jadwal_ujian','id');
    }

    public function matakuliah()
    {
        return $this->belongsTo('App\Matakuliah','id_matakuliah','id');
    }

    public function fakultas()
    {
        return $this->belongsTo('App\Fakultas','id_fakultas','id');
    }

    public function prodi()
    {
        return $this->belongsTo('App\Prodi','id_prodi','id');
    }
}

app/Http/Controllers/ArsipNilaiController.php
<?php

namespace App\Http\Controllers;

use App\ArsipNilai;
use App\User;
use App\Kurikulum;
use App\JenisUjian;
use App\Matakuliah;
use App\Fakultas;
use App\Prodi;
use File;
use App\TahunAjaran;
use App\JadwalUjian;
use Illuminate\Http\Request;
use App\Http\Requests\ArsipNilaiRequest;

class ArsipNilaiController extends Controller
{

    public function __construct()
    {
        $this->middleware('kaprodi.auth')->except('index','show','exportPdf');
    }

     public function index()
    {
        $dataArsipNilai = ArsipNilai::orderBy('id','DESC')->get();
        return view('admin.arsip_nilai.index',compact('dataArsipNilai'));
    }

    public function create()
    {
        $dataUser       = User::where('role_id',3)->get();
        $dataKurikulum  = Kurikulum::all();
        $dataJenisUjian = JenisUjian::all();
        $dataMatakuliah = Matakuliah::all();
        $dataFakultas   = Fakultas::all();
        $dataProdi      = Prodi::all();
        $dataTahunAjaran = TahunAjaran::all();
        $dataJadwalUjian = JadwalUjian::all();
        
        return view('admin.arsip_nilai.create',compact('dataUser','dataKurikulum','dataJenisUjian','dataMatakuliah','dataFakultas','dataProdi','dataTahunAjaran','dataJadwalUjian'));
    }

    public function store(ArsipNilaiRequest $request)
    {
        $input = $request->all();

        if($request->hasFile('nilai'))
        {
            $file_name  = $request->nilai->hashName();
            $input['nilai'] = $file_name;
            $request->file('nilai')->store('public/nilai');
        }

        ArsipNilai::create($input);
        return redirect()->route('arsip-nilai.index')->with('flash_message','tambah data arsip nilai berhasil');
    }

    public function show(ArsipNilai $arsipNilai)
    {
        return view('admin.arsip_nilai.show',compact('arsipNilai'));
    }

    public function destroy(ArsipNilai $arsipNilai)
    {
        File::delete(storage_path('app/public/nilai/'.$arsipNilai->nilai));
        $arsipNilai->delete();
        return redirect()->route('arsip-nilai.index')->with('flash_message','hapus data arsip nilai berhasil');
    }

    public function exportPdf($id)
    {
        $data = \App\ArsipNilai::find($id);
        $filename= asset('storage/Nilai/'.$data->nilai);
        $cek = getimagesize($filename);
        $width  = $cek[0];
        $height = $cek[1];

        if($width > $height){
            $condition          = 'landscape';
            $data['condition']  = 'width';
        } else {
            $condition          = 'portrait';
            $data['condition'] = 'height';
        }

        // return $data->condition;

        $pdf = \PDF::loadView('pdf.arsip_nilai', ["data" => $data])->setPaper('f4', $condition);
        return $pdf->download(date("Y-m-d H:i:s").'_arsip_nilai.pdf');
    }
}

resources/views/admin/arsip_nilai/create.blade.php
@extends('admin.layouts.app')

@section('title','Tambah Jadwal Ujian')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Tambah Arsip nilai
				<small>Admin Akademik</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Forms</a></li>
				<li class="active">General Elements</li>
			</ol>
		</section>

		<!-- Main content -->
		<section class="content">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="box box-primary">
						<div class="box-header with-border">
							<a href="{{ route('arsip-nilai.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
						</div>
						<!-- form start -->
						<form method="POST" role="form" action="{{ route('arsip-nilai.store') }}" enctype="multipart/form-data">
							@csrf
							<div class="box-body">
								@if($errors->any())
									<div class="form-group {{ $errors->has('kode_nilai') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Kode Nilai</label>
									<input type="text" class="form-control" id="" placeholder="Kode Nilai" name="kode_nilai" value="{{ old('kode_nilai') }}">
									<span class="help-block">{{ $errors->first('kode_nilai') }}</span>
                                </div>
                                
                                @if($errors->any())
									<div class="form-group {{ $errors->has('nilai') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Nilai</label>
									<input type="file" class="form-control" id="" placeholder="nilai" name="nilai" value="{{ old('nilai') }}">
									<span class="help-block">{{ $errors->first('nilai') }}</span>
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_user') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">NIDN</label>
									<select name="id_user" id="" class="form-control">
										<option value="">NIDN</option>
                                        @foreach($dataUser as $user)
                                            <option value="{{ $user->id }}" {{ old('id_user') == $user->id ? 'selected' : '' }}>{{ $user->nomor_induk }} - {{ $user->nama_lengkap }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_user') }}</span>																				
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_kurikulum') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Kode Kurikulum</label>
									<select name="id_kurikulum" id="" class="form-control">
										<option value="">Kode Kurikulum</option>
                                        @foreach($dataKurikulum as $kurikulum)
                                            <option value="{{ $kurikulum->id }}" {{ old('id_kurikulum') == $kurikulum->id ? 'selected' : '' }}>{{ $kurikulum->kode_kurikulum }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_kurikulum') }}</span>																				
								</div>
								
									 @if($errors->any())
									<div class="form-group {{ $errors->has('id_jadwal_ujian') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Kode Jadwal Ujian</label>
									<select name="id_jadwal_ujian" id="" class="form-control">
										<option value="">Kode Jadwal Ujian</option>
                                        @foreach($dataJadwalUjian as $jadwal_ujian)
                                            <option value="{{ $jadwal_ujian->id }}" {{ old('id_jadwal_ujian') == $jadwal_ujian->id ? 'selected' : '' }}>{{ $jadwal_ujian->kode_jadwal_ujian }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_jadwal_ujian') }}</span>																				
								</div>
								
								
								 @if($errors->any())
									<div class="form-group {{ $errors->has('id_tahun_ajaran') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Kode Tahun Ajaran</label>
									<select name="id_tahun_ajaran" id="" class="form-control">
										<option value="">Kode Tahun Ajaran</option>
                                        @foreach($dataTahunAjaran as $tahun_ajaran)
                                            <option value="{{ $tahun_ajaran->id }}" {{ old('id_tahun_ajaran') == $tahun_ajaran->id ? 'selected' : '' }}>{{ $tahun_ajaran->kode_tahun_ajaran }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_tahun_ajaran') }}</span>																				
                                </div>

                                 @if($errors->any())
									<div class="form-group {{ $errors->has('id_jenis_ujian') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Jenis Ujian</label>
									<select name="id_jenis_ujian" id="" class="form-control">
										<option value="">Jenis Ujian</option>
                                        @foreach($dataJenisUjian as $jenisUjian)
                                            <option value="{{ $jenisUjian->id }}" {{ old('id_jenis_ujian') == $jenisUjian->id ? 'selected' : '' }}>{{ $jenisUjian->jenis_ujian }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_jenis_ujian') }}</span>																				
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_matakuliah') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">kode matakuliah</label>
									<select name="id_matakuliah" id="" class="form-control">
										<option value="">kode matakuliah</option>
                                        @foreach($dataMatakuliah as $matakuliah)
                                            <option value="{{ $matakuliah->id }}" {{ old('id_matakuliah') == $matakuliah->id ? 'selected' : '' }}>{{ $matakuliah->kode_matakuliah }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_matakuliah') }}</span>																				
                                </div>

                                @if($errors->any())
                                    <div class="form-group {{ $errors->has('id_fakultas') ? 'has-error' : 'has-success' }}">
                                @else
                                    <div class="form-group">
                                @endif
                                    <label for="">kode fakultas</label>
                                    <select name="id_fakultas" id="" class="form-control">
                                        <option value="">kode fakultas</option>
                                        @foreach($dataFakultas as $fakultas)
                                            <option value="{{ $fakultas->id }}" {{ old('id_fakultas') == $fakultas->id ? 'selected' : '' }}>{{ $fakultas->kode_fakultas }}</option>
                                        @endforeach
                                    </select>
                                    <span class="help-block">{{ $errors->first('id_fakultas') }}</span>																				
                                </div>

                                @if($errors->any())
                                    <div class="form-group {{ $errors->has('id_prodi') ? 'has-error' : 'has-success' }}">
                                @else
                                    <div class="form-group">
                                @endif
                                    <label for="">Kode Prodi</label>
                                    <select name="id_prodi" id="" class="form-control">
                                        <option value="">Kode Prodi</option>
                                        @foreach($dataProdi as $prodi)
                                            <option value="{{ $prodi->id }}" {{ old('id_prodi') == $prodi->id ? 'selected' : '' }}>{{ $prodi->kode_prodi }}</option>
                                        @endforeach
                                    </select>
                                    <span class="help-block">{{ $errors->first('id_prodi') }}</span>																				
                                </div>

							<div class="box-footer">
							<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- /.row -->
		</section>
		<!-- /.content -->
	</div>
@endsection

resources/views/admin/arsip_nilai/index.blade.php
@extends('admin.layouts.app')

@section('title','Arsip nilai')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Arsip nilai
                <small>admin akademik</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            @if(auth::user()->role_id != 2)
                                <a href="{{ route('arsip-nilai.create') }}"><button class="btn btn-primary"><i class="fa fa-plus"></i> tambah data</button></a>
                            @endif
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            @include('admin._partial.flash_message')
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Kode Nilai</th>
                                        <th>Kode Kurikulum</th>
                                        <th>Kode Jenis Ujian</th>
                                        <th>Kode Matakuliah</th>
                                        <th>NIDN</th>
                                        <th>Kode Fakultas</th>
                                        <th>Kode Prodi</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($dataArsipNilai as $arsipNilai)
                                        <tr>
                                            <td>{{ $arsipNilai->kode_nilai }}</td>
                                            <td>{{ $arsipNilai->kurikulum->kode_kurikulum }}</td>
                                            <td>{{ $arsipNilai->jenisUjian->kode_jenis_ujian }}</td>
                                            <td>{{ $arsipNilai->matakuliah->kode_matakuliah }}</td>
                                            <td>{{ $arsipNilai->user->nomor_induk }}</td>
                                            <td>{{ $arsipNilai->fakultas->kode_fakultas }}</td>
                                            <td>{{ $arsipNilai->prodi->kode_prodi }}</td>
                                            <td>
                                                <a data-toggle="tooltip" data-placement="bottom" title="detail" href="{{ route('arsip-nilai.show',$arsipNilai->id) }}"><button class="btn btn-sm btn-info"><i class="fa fa-th"></i></button></a>                                                
                                                <a data-toggle="tooltip" data-placement="bottom" title="download nilai" href="{{ route('arsip_nilai.pdf',$arsipNilai->id) }}"><button class="btn btn-sm btn-success"><i class="fa fa-download"></i></button></a>                                                
                                                @if(auth::user()->role_id != 2)
                                                    <form action="{{ route('arsip-nilai.destroy',$arsipNilai->id) }}" style="display:inline-block;" method="POST" id="deleteData_{{ $arsipNilai->id }}">
                                                        @csrf
                                                        {{ method_field('DELETE') }}
                                                        <button data-toggle="tooltip" data-placement="bottom" title="delete" class="btn btn-danger delete btn-sm" id="{{ $arsipNilai->id }}"><i class="fa fa-trash"></i></button>
                                                    </form>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script src="{{ asset('assets/dist/js/sweetalert.min.js') }}"></script>
    <script>
    $(function () {
        $('#example1').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": false,
            "info": true,
            "autoWidth": false
        });

        $(document).on('click','.delete',function(e){
            e.preventDefault();
            var idForm = $(this).attr('id');
            swal({
                title: "Apakah anda yakin akan menghapus data arsip nilai ?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                $('#deleteData_'+idForm).submit();
                swal("Data Terhapus", {
                    icon: "success", 
                });
                } else {
                swal("Data Masih Tersimpan"); 
                }
            });
        });
    });
    </script>
@endsection

resources/views/admin/arsip_nilai/show.blade.php
@extends('admin.layouts.app')

@section('title','Detail matakuliah')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Arsip Nilai
                <small>admin akademik</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <a href="{{ route('arsip-nilai.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Dosen</th>
                                        <td>{{ $arsipNilai->user->nama_lengkap }}</td>
                                    </tr>
                                     <tr>
                                        <th>Kode Kurikulum</th>
                                        <td>{{ $arsipNilai->kurikulum->kode_kurikulum }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Jenis Ujian</th>
                                        <td>{{ $arsipNilai->jenisUjian->kode_jenis_ujian }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Tahun Ajaran</th>
                                        <td>{{ $arsipNilai->tahunAjaran->kode_tahun_ajaran }}</td>
                                    </tr>
                                     <tr>
                                        <th>Kode Jadwal Ujian</th>
                                        <td>{{ $arsipNilai->JadwalUjian->kode_jadwal_ujian }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Mata Kuliah</th>
                                    <td>{{ $arsipNilai->mataKuliah->kode_matakuliah }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Fakultas</th>
                                        <td>{{ $arsipNilai->fakultas->kode_fakultas }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Prodi</th>
                                        <td>{{ $arsipNilai->prodi->kode_prodi }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Nilai</th>
                                        <td>{{ $arsipNilai->kode_nilai }}</td>
                                    </tr>
                                    <tr>
                                        <th>Nilai</th>
                                        <td>
                                            <img src="{{ asset('storage/nilai/'.$arsipNilai->nilai) }}" width="300px" alt="">
                                        </td>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection