routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear',function(){
  \Artisan::call('config:cache');
return "ada";
});


Route::group(['middleware' => 'auth'],function() {
    Route::get('','DashboardController@index')->name('dashboard')->middleware('kaprodi.auth');

    Route::resource('user','UserController')->middleware('kaprodi.auth');

    Route::resource('fakultas','FakultasController',['parameters' => [
        'fakultas'  => 'fakultas'
    ]])->except(['show'])->middleware('kaprodi.auth');

    Route::resource('prodi','ProdiController')->except(['show'])->middleware('kaprodi.auth');

    Route::resource('kelas','KelasController',['parameters' => [
        'kelas' => 'kelas'
    ]])->except(['show'])->middleware('kaprodi.auth');

    Route::resource('matakuliah','MatakuliahController')->middleware('kaprodi.auth');
    Route::resource('tahun-ajaran','TahunAjaranController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('kurikulum','KurikulumController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('jenis-ujian','JenisUjianController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('jadwal-ujian','JadwalUjianController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('arsip-soal','ArsipSoalController')->except(['edit','update']);
    Route::resource('arsip-nilai','ArsipNilaiController')->except(['edit','update']);

    // export pdf
    Route::get('arsip-soal/pdf/{id}','ArsipSoalController@exportPdf')->name('arsip_soal.pdf');
    Route::get('arsip-nilai/pdf/{id}','ArsipNilaiController@exportPdf')->name('arsip_nilai.pdf');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Matakuliah.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Matakuliah extends Model
{
    protected $table = 'matakuliah';

    protected $fillable = [
        'id_user',
        'id_prodi',
        'id_fakultas',
        'id_kelas',
        'kode_matakuliah',
        'matakuliah',
        'sks',
        'semester'
    ];

    public function user()
    {
        return $this->belongsTo('App\User','id_user','id');
    }

    public function prodi()
    {
        return $this->belongsTo('App\Prodi','id_prodi','id');
    }

    public function fakultas()
    {
        return $this->belongsTo('App\Fakultas','id_fakultas','id');
    }

    public function kelas()
    {
        return $this->belongsTo('App\Kelas','id_kelas','id');
    }

    public function kurikulum()
    {
        return $this->hasMany('App\Kurikulum','id_matakuliah','id');
    }

    public function jadwalUjian()
    {
        return $this->hasMany('App\JadwalUjian','id_matakuliah','id');
    }

    public function arsipSoal()
    {
        return $this->hasMany('App\ArsipSoal','id_matakuliah','id');
    }

     public function arsipNilai()
    {
        return $this->hasMany('App\ArsipNilai','id_matakuliah','id');
    }
    
}

app/Http/Controllers/MatakuliahController.php
<?php

namespace App\Http\Controllers;

use App\Matakuliah;
use App\User;
use App\Fakultas;
use App\Prodi;
use App\Kelas;
use Illuminate\Http\Request;
use App\Http\Requests\MatakuliahRequest;

class MatakuliahController extends Controller
{

    public function index()
    {
        $dataMatakuliah = Matakuliah::orderBy('id','DESC')->get();
        return view('admin.matakuliah.index',compact('dataMatakuliah'));
    }

    public function create()
    {
        $dataUser       = User::where('role_id',3)->get();
        $dataFakultas   = Fakultas::all();
        $dataProdi      = Prodi::all();
        $dataKelas      = Kelas::all();
        return view('admin.matakuliah.create',compact('dataUser','dataFakultas','dataProdi','dataKelas'));
    }

    public function store(MatakuliahRequest $request)
    {
        Matakuliah::create($request->all());
        return redirect()->route('matakuliah.index')->with('flash_message','tambah data matakakuliah berhasil');
    }

    public function show(Matakuliah $matakuliah)
    {
        return view('admin.matakuliah.show',compact('matakuliah'));
    }

    public function edit(Matakuliah $matakuliah)
    {
        $dataUser       = User::where('role_id',3)->get();
        $dataFakultas   = Fakultas::all();
        $dataProdi      = Prodi::all();
        $dataKelas      = Kelas::all();
        return view('admin.matakuliah.edit',compact('matakuliah','dataUser','dataFakultas','dataProdi','dataKelas'));
    }

    public function update(MatakuliahRequest $request, Matakuliah $matakuliah)
    {
        $matakuliah->update($request->all());
        return redirect()->route('matakuliah.index')->with('flash_message','update data matakuliah berhasil');
    }

    public function destroy(Matakuliah $matakuliah)
    {
        $matakuliah->delete();
        return redirect()->route('matakuliah.index')->with('flash_message','hapus data matakuliah berhasil');
    }
}

resources/views/admin/matakuliah/create.blade.php
@extends('admin.layouts.app')

@section('title','Tambah Matakuliah')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Tambah Matakuliah
				<small>Admin Akademik</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Forms</a></li>
				<li class="active">General Elements</li>
			</ol>
		</section>

		<!-- Main content -->
		<section class="content">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="box box-primary">
						<div class="box-header with-border">
							<a href="{{ route('matakuliah.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
						</div>
						<!-- form start -->
						<form method="POST" role="form" action="{{ route('matakuliah.store') }}">
							@csrf
							<div class="box-body">
								@if($errors->any())
									<div class="form-group {{ $errors->has('kode_matakuliah') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Kode Matakuliah</label>
									<input type="text" class="form-control" id="" placeholder="Kode Matakuliah" name="kode_matakuliah" value="{{ old('kode_matakuliah') }}">
									<span class="help-block">{{ $errors->first('kode_matakuliah') }}</span>
                                </div>
                                

								@if($errors->any())
									<div class="form-group {{ $errors->has('matakuliah') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Matakuliah</label>
									<input type="text" class="form-control" id="" placeholder="matakuliah" name="matakuliah" value="{{ old('matakuliah') }}">
									<span class="help-block">{{ $errors->first('matakuliah') }}</span>										
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('sks') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">SKS</label>
									<input type="text" class="form-control" id="" placeholder="sks" name="sks" value="{{ old('sks') }}">
									<span class="help-block">{{ $errors->first('sks') }}</span>										
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('semester') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Semester</label>
									<select name="semester" id="" class="form-control">
										<option value="">semester</option>
                                        <option value="ganjil" {{ old('semester') == "ganjil" ? 'selected' : '' }}>ganjil</option>
                                        <option value="genap" {{ old('semester') == "genap" ? 'selected' : '' }}>genap</option>
									</select>
									<span class="help-block">{{ $errors->first('semester') }}</span>																				
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_prodi') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">kode Prodi</label>
									<select name="id_prodi" id="" class="form-control">
										<option value="">kode Prodi</option>
                                        @foreach($dataProdi as $prodi)
                                            <option value="{{ $prodi->id }}" {{ old('id_prodi') == $prodi->id ? 'selected' : '' }}>{{ $prodi->kode_prodi }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_prodi') }}</span>																				
                                </div>

                                
                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_fakultas') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">kode fakultas</label>
									<select name="id_fakultas" id="" class="form-control">
										<option value="">kode fakultas</option>
                                        @foreach($dataFakultas as $fakultas)
                                            <option value="{{ $fakultas->id }}" {{ old('id_fakultas') == $fakultas->id ? 'selected' : '' }}>{{ $fakultas->kode_fakultas }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_fakultas') }}</span>																				
                                </div>
                                

								@if($errors->any())
									<div class="form-group {{ $errors->has('id_user') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">NIDN</label>
									<select name="id_user" id="" class="form-control">
										<option value="">NIDN</option>
                                        @foreach($dataUser as $user)
                                            <option value="{{ $user->id }}" {{ old('id_user') == $user->id ? 'selected' : '' }}>{{ $user->nomor_induk }} - {{ $user->nama_lengkap }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_user') }}</span>																				
                                </div>
                                
                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_kelas') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">kode kelas</label>
									<select name="id_kelas" id="" class="form-control">
										<option value="">kode kelas</option>
                                        @foreach($dataKelas as $kelas)
                                            <option value="{{ $kelas->id }}" {{ old('id_kelas') == $kelas->id ? 'selected' : '' }}>{{ $kelas->kode_kelas }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_kelas') }}</span>																				
                                </div>

							<div class="box-footer">
							<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- /.row -->
		</section>
		<!-- /.content -->
	</div>
@endsection

resources/views/admin/matakuliah/edit.blade.php
@extends('admin.layouts.app')

@section('title','Tambah Matakuliah')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Edit Matakuliah
				<small>Admin Akademik</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Forms</a></li>
				<li class="active">General Elements</li>
			</ol>
		</section>

		<!-- Main content -->
		<section class="content">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="box box-primary">
						<div class="box-header with-border">
				 			<a href="{{ route('matakuliah.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
						</div>
						<!-- form start -->
						<form method="POST" role="form" action="{{ route('matakuliah.update',$matakuliah->id) }}">
                            @csrf
                            {{ method_field('PATCH') }}
                           <input type="hidden" name="id" value="{{ $matakuliah->id }}">
							<div class="box-body">
								@if($errors->any())
									<div class="form-group {{ $errors->has('kode_matakuliah') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Kode Matakuliah</label>
									<input type="text" class="form-control" id="" placeholder="Kode Matakuliah" name="kode_matakuliah" value="{{ $errors->any() ? old('kode_matakuliah') : $matakuliah->kode_matakuliah }}">
									<span class="help-block">{{ $errors->first('kode_matakuliah') }}</span>
                                </div>
                                

								@if($errors->any())
									<div class="form-group {{ $errors->has('matakuliah') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Matakuliah</label>
									<input type="text" class="form-control" id="" placeholder="matakuliah" name="matakuliah" value="{{ $errors->any() ? old('matakuliah') : $matakuliah->matakuliah }}">
									<span class="help-block">{{ $errors->first('matakuliah') }}</span>										
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('sks') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">SKS</label>
									<input type="text" class="form-control" id="" placeholder="sks" name="sks" value="{{ $errors->any() ? old('sks') : $matakuliah->sks }}">
									<span class="help-block">{{ $errors->first('sks') }}</span>										
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('semester') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Semester</label>
									<select name="semester" id="" class="form-control">
										<option value="">semester</option>
                                        <option value="ganjil" {{ $errors->any() ? (old('semester') == "ganjil" ? 'selected' : '') : ($matakuliah->semester == "ganjil" ? 'selected' : '') }}>ganjil</option>
                                        <option value="genap" {{ $errors->any() ? (old('semester') == "genap" ? 'selected' : '') : ($matakuliah->semester == "genap" ? 'selected' : '') }}>genap</option>
									</select>
									<span class="help-block">{{ $errors->first('semester') }}</span>																				
                                </div>

                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_prodi') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">kode Prodi</label>
									<select name="id_prodi" id="" class="form-control">
										<option value="">kode Prodi</option>
                                        @foreach($dataProdi as $prodi)
                                            <option value="{{ $prodi->id }}" {{ $errors->any() ? (old('id_prodi') == $prodi->id ? 'selected' : '') : ($matakuliah->id_prodi == $prodi->id ? 'selected' : '') }}>{{ $prodi->kode_prodi }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_prodi') }}</span>																				
                                </div>

                                
                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_fakultas') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">kode fakultas</label>
									<select name="id_fakultas" id="" class="form-control">
										<option value="">kode fakultas</option>
                                        @foreach($dataFakultas as $fakultas)
                                            <option value="{{ $fakultas->id }}" {{ $errors->any() ? (old('id_fakultas') == $fakultas->id ? 'selected' : '') : ($matakuliah->id_fakultas == $fakultas->id ? 'selected' : '') }}>{{ $fakultas->kode_fakultas }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_fakultas') }}</span>																				
                                </div>
                                

								@if($errors->any())
									<div class="form-group {{ $errors->has('id_user') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">NIDN</label>
									<select name="id_user" id="" class="form-control">
										<option value="">NIDN</option>
                                        @foreach($dataUser as $user)
                                            <option value="{{ $user->id }}" {{ $errors->any() ? (old('id_user') == $user->id ? 'selected' : '') : ($matakuliah->id_user == $user->id ? 'selected' : '') }}>{{ $user->nomor_induk }} - {{ $user->nama_lengkap }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_user') }}</span>																				
                                </div>
                                
                                @if($errors->any())
									<div class="form-group {{ $errors->has('id_kelas') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">kode kelas</label>
									<select name="id_kelas" id="" class="form-control">
										<option value="">kode kelas</option>
                                        @foreach($dataKelas as $kelas)
                                            <option value="{{ $kelas->id }}" {{ $errors->any() ? (old('id_kelas') == $kelas->id ? 'selected' : '') : ($matakuliah->id_kelas == $kelas->id ? 'selected' : '') }}>{{ $kelas->kode_kelas }}</option>
                                        @endforeach
									</select>
									<span class="help-block">{{ $errors->first('id_kelas') }}</span>																				
                                </div>

							<div class="box-footer">
							<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- /.row -->
		</section>
		<!-- /.content -->
	</div>
@endsection

resources/views/admin/matakuliah/index.blade.php
@extends('admin.layouts.app')

@section('title','Matakuliah')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Matakuliah
                <small>admin akademik</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <a href="{{ route('matakuliah.create') }}"><button class="btn btn-primary"><i class="fa fa-plus"></i> tambah data</button></a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            @include('admin._partial.flash_message')
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Kode Matakuliah</th>
                                        <th>Matakuliah</th>
                                        <th>SKS</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($dataMatakuliah as $matakuliah)
                                        <tr>
                                            <td>{{ $matakuliah->kode_matakuliah }}</td>
                                            <td>{{ $matakuliah->matakuliah }}</td>
                                            <td>{{ $matakuliah->sks }}</td>
                                            <td>
                                                    <a data-toggle="tooltip" data-placement="bottom" title="detail" href="{{ route('matakuliah.show',$matakuliah->id) }}"><button class="btn btn-sm btn-info"><i class="fa fa-th"></i></button></a>
                                                    <a data-toggle="tooltip" data-placement="bottom" title="edit" href="{{ route('matakuliah.edit',$matakuliah->id) }}"><button class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></button></a>
                                                    <form action="{{ route('matakuliah.destroy',$matakuliah->id) }}" style="display:inline-block;" method="POST" id="deleteData_{{ $matakuliah->id }}">
                                                        @csrf
                                                        {{ method_field('DELETE') }}
                                                        <button data-toggle="tooltip" data-placement="bottom" title="delete" class="btn btn-danger btn-sm delete" id="{{ $matakuliah->id }}"><i class="fa fa-trash"></i></button>
                                                    </form>
                                                </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script src="{{ asset('assets/dist/js/sweetalert.min.js') }}"></script>
    <script>
    $(function () {
        $('#example1').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": false,
            "info": true,
            "autoWidth": false
        });

         $(document).on('click','.delete',function(e){
            e.preventDefault();
            var idForm = $(this).attr('id');
            swal({
                title: "Apakah anda yakin akan menghapus data matakuliah ?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                $('#deleteData_'+idForm).submit();
                swal("Data Terhapus", {
                    icon: "success", 
                });
                } else {
                swal("Data Masih Tersimpan"); 
                }
            });
        });
    });
    </script>
@endsection

resources/views/admin/matakuliah/show.blade.php
@extends('admin.layouts.app')

@section('title','Detail matakuliah')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                matakuliah
                <small>admin akademik</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <a href="{{ route('matakuliah.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Kode Matakuliah</th>
                                        <td>{{ $matakuliah->kode_matakuliah }}</td>
                                    </tr>
                                     <tr>
                                        <th>Matakuliah</th>
                                        <td>{{ $matakuliah->matakuliah }}</td>
                                    </tr>
                                    <tr>
                                        <th>SKS</th>
                                    <td>{{ $matakuliah->sks }}</td>
                                    </tr>
                                    <tr>
                                        <th>Semester</th>
                                        <td>{{ $matakuliah->semester }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Prodi</th>
                                        <td>{{ $matakuliah->prodi->kode_prodi }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Fakultas</th>
                                        <td>{{ $matakuliah->fakultas->kode_fakultas }}</td>
                                    </tr>
                                    <tr>
                                        <th>NIDN</th>
                                        <td>{{ $matakuliah->user->nomor_induk }}</td>
                                    </tr>
                                    <tr>
                                        <th>Kode Kelas</th>
                                        <td>{{ $matakuliah->kelas->kode_kelas }}</td>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection