routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear',function(){
  \Artisan::call('config:cache');
return "ada";
});


Route::group(['middleware' => 'auth'],function() {
    Route::get('','DashboardController@index')->name('dashboard')->middleware('kaprodi.auth');

    Route::resource('user','UserController')->middleware('kaprodi.auth');

    Route::resource('fakultas','FakultasController',['parameters' => [
        'fakultas'  => 'fakultas'
    ]])->except(['show'])->middleware('kaprodi.auth');

    Route::resource('prodi','ProdiController')->except(['show'])->middleware('kaprodi.auth');

    Route::resource('kelas','KelasController',['parameters' => [
        'kelas' => 'kelas'
    ]])->except(['show'])->middleware('kaprodi.auth');

    Route::resource('matakuliah','MatakuliahController')->middleware('kaprodi.auth');
    Route::resource('tahun-ajaran','TahunAjaranController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('kurikulum','KurikulumController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('jenis-ujian','JenisUjianController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('jadwal-ujian','JadwalUjianController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('arsip-soal','ArsipSoalController')->except(['edit','update']);
    Route::resource('arsip-nilai','ArsipNilaiController')->except(['edit','update']);

    // export pdf
    Route::get('arsip-soal/pdf/{id}','ArsipSoalController@exportPdf')->name('arsip_soal.pdf');
    Route::get('arsip-nilai/pdf/{id}','ArsipNilaiController@exportPdf')->name('arsip_nilai.pdf');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'nama_lengkap','nomor_induk','email', 'password','role_id'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function profil()
    {
        return $this->hasOne('App\Profil','id_user','id');
    }

    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    public function fakultas()
    {
        return $this->hasMany('App\Fakultas','id_user','id');
    }

    public function prodi()
    {
        return $this->hasMany('App\Prodi','id_user','id');
    }

    public function matakuliah()
    {
        return $this->hasMany('App\Matakuliah','id_user','id');
    }

    public function kurikulum()
    {
        return $this->hasMany('App\Kurikulum','id_user','id');
    }

    public function jadwalUjian()
    {
        return $this->hasMany('App\JadwalUjian','id_user','id');
    }

    public function arsipSoal()
    {
        return $this->hasMany('App\ArsipSoal','id_user','id');
    }

    public function arsipNilai()
    {
        return $this->hasMany('App\ArsipNilai','id_user','id');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use App\User;
use App\Profil;
use File;

class UserController extends Controller
{

    public function index()
    {
        $users = User::orderBy('id','DESC')->get();
        return view('admin.user.index',compact('users'));
    }

    public function create()
    {
        $roles = \App\Role::all();
        return view('admin.user.create',compact('roles'));
    }

    public function store(UserRequest $request)
    {
        $input              = $request->all();
        $input['password']  = bcrypt($request->password);
        $user               = User::create($input);
        $input['id_user']   = $user->id;

        if($request->hasFile('foto'))
        {
            $file_name  = $request->foto->hashName();
            $input['foto'] = $file_name;
            $request->file('foto')->store('public/profil');
        }

        Profil::create($input);
        return redirect()->route('user.index')->with('flash_message','tambah data user berhasil');
    }

    public function show(User $user)
    {
        return view('admin.user.show',compact('user'));
    }

    public function edit(User $user)
    {
        $roles = \App\Role::all();
        return view('admin.user.edit',compact('user','roles'));
    }

    public function update(UserRequest $request, User $user)
    {
        $input = $request->all();

        $user->update($input);

        if($request->hasFile('foto'))
        {
            File::delete(storage_path('app/public/profil/'.$user->profil->foto));
            $file_name      = $request->foto->hashName();
            $input['foto'] = $file_name;
            $request->file('foto')->store('public/profil');
        }

        $user->profil->update($input);

        return redirect()->route('user.index')->with('flash_message','update data user berhasil');
    }

    public function destroy(User $user)
    {
        File::delete(storage_path('app/public/profil/'.$user->profil->foto));
        $user->delete();
        return redirect()->route('user.index')->with('flash_message','hapus data user berhasil');
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app')

@section('title','Tambah User')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Tambah User
				<small>Admin Akademik</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Forms</a></li>
				<li class="active">General Elements</li>
			</ol>
		</section>

		<!-- Main content -->
		<section class="content">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="box box-primary">
						<div class="box-header with-border">
							<a href="{{ route('user.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
						</div>
						<!-- form start -->
						<form method="POST" role="form" action="{{ route('user.store') }}" enctype="multipart/form-data">
							@csrf
							<div class="box-body">
								@if($errors->any())
									<div class="form-group {{ $errors->has('nama_lengkap') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Nama lengkap</label>
									<input type="text" class="form-control" id="" placeholder="Nama Lengkap" name="nama_lengkap" value="{{ old('nama_lengkap') }}">
									<span class="help-block">{{ $errors->first('nama_lengkap') }}</span>
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('nomor_induk') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Nomor Induk</label>
									<input type="text" class="form-control" id="" placeholder="Nomor Induk" name="nomor_induk" value="{{ old('nomor_induk') }}">
									<span class="help-block">{{ $errors->first('nomor_induk') }}</span>
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('jenis_kelamin') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Jenis Kelamin</label>
									<select name="jenis_kelamin" id="" class="form-control">
										<option value="">Jenis Kelamin</option>
										<option value="laki-laki" {{ old('jenis_kelamin') == "laki-laki" ? 'selected' : '' }}>Laki-laki</option>
										<option value="perempuan" {{ old('jenis_kelamin') == "perempuan" ? 'selected' : '' }}>Perempuan</option>
									</select>
									<span class="help-block">{{ $errors->first('jenis_kelamin') }}</span>
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('tempat_lahir') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">tempat lahir</label>
									<input type="text" class="form-control" id="" placeholder="Tempat Lahir" name="tempat_lahir" value="{{ old('tempat_lahir') }}">
									<span class="help-block">{{ $errors->first('tempat_lahir') }}</span>										
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('tanggal_lahir') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Tanggal Lahir</label>
									<input type="date" class="form-control" name="tanggal_lahir" id="" placeholder="Tanggal Lahir" value="{{ old('tanggal_lahir') }}">
									<span class="help-block">{{ $errors->first('tanggal_lahir') }}</span>																				
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('agama') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Agama</label>
									<select name="agama" id="" class="form-control">
										<option value="">Agama</option>
										<option value="islam" {{ old('agama') == "islam" ? "selected" : "" }}>islam</option>
										<option value="kristen" {{ old('agama') == "kristen" ? "selected" : "" }}>kristen</option>
										<option value="budha" {{ old('agama') == "budha" ? "selected" : "" }}>budha</option>
										<option value="hindu" {{ old('agama') == "hindu" ? "selected" : "" }}>hindu</option>
									</select>
									<span class="help-block">{{ $errors->first('agama') }}</span>																				
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('telepon') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Telepon</label>
									<input type="text" class="form-control" id="" placeholder="Telepon" name="telepon" value="{{ old('telepon') }}">
									<span class="help-block">{{ $errors->first('telepon') }}</span>																												
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('alamat') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">alamat</label>
									<textarea name="alamat" id="" cols="30" rows="10" placeholder="alamat" class="form-control">{{ old('alamat') }}</textarea>
									<span class="help-block">{{ $errors->first('alamat') }}</span>																												
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('role_id') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Role</label>
									<select name="role_id" id="" placeholder="Role" class="form-control">
										<option value="">Role</option>
										@foreach($roles as $role)
									<option value="{{ $role->id }}" {{ $role->id == old('role_id') ? 'selected' : '' }}>{{ $role->role }}</option>
										@endforeach
									</select>
									<span class="help-block">{{ $errors->first('role_id') }}</span>																				
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('email') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Email</label>
									<input type="email" class="form-control" id="" placeholder="Email" name="email" value="{{ old('email') }}">
									<span class="help-block">{{ $errors->first('email') }}</span>																												
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('password') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Password</label>
									<input type="password" class="form-control" id="" placeholder="Password" name="password" value="{{ old('password') }}">
									<span class="help-block">{{ $errors->first('password') }}</span>																														
								</div>

								<div class="form-group">
									<label for="">Password Confirmation</label>
									<input type="password" class="form-control" id="" placeholder="Password Confirmation" name="password_confirmation">
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('foto') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Foto</label>
									<input type="file" class="form-control" id="" placeholder="Foto" name="foto">
									<span class="help-block">{{ $errors->first('foto') }}</span>																												
								</div>
							</div>
							<!-- /.box-body -->

							<div class="box-footer">
							<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- /.row -->
		</section>
		<!-- /.content -->
	</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('title','Tambah User')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Edit User
				<small>Admin Akademik</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Forms</a></li>
				<li class="active">General Elements</li>
			</ol>
		</section>

		<!-- Main content -->
		<section class="content">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="box box-primary">
						<div class="box-header with-border">
							<a href="{{ route('user.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
						</div>
						<!-- form start -->
						<form method="POST" role="form" action="{{ route('user.update',$user->id) }}" enctype="multipart/form-data">
							@csrf
							{{ method_field('PATCH') }}
							<input type="hidden" value="{{ $user->id }}" name="id">
							<div class="box-body">
								@if($errors->any())
									<div class="form-group {{ $errors->has('nama_lengkap') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Nama lengkap</label>
									<input type="text" class="form-control" id="" placeholder="Nama Lengkap" name="nama_lengkap" value="{{ $errors->any() ? old('nama_lengkap') : $user->nama_lengkap }}">
									<span class="help-block">{{ $errors->first('nama_lengkap') }}</span>
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('nomor_induk') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Nomor Induk</label>
									<input type="text" class="form-control" id="" placeholder="Nomor Induk" name="nomor_induk" value="{{ $errors->any() ? old('nomor_induk') : $user->nomor_induk }}">
									<span class="help-block">{{ $errors->first('nomor_induk') }}</span>
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('jenis_kelamin') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Jenis Kelamin</label>
									<select name="jenis_kelamin" id="" class="form-control">
										<option value="">Jenis Kelamin</option>
										<option value="laki-laki" {{ $errors->any() ? (old('jenis_kelamin') == "laki-laki" ? 'selected' : '') : ($user->profil->jenis_kelamin == "laki-laki" ? "selected" : "") }}>Laki-laki</option>
										<option value="perempuan" {{ $errors->any() ? (old('jenis_kelamin') == "perempuan" ? 'selected' : '') : ($user->profil->jenis_kelamin == "perempuan" ? "selected" : "") }}>Perempuan</option>
									</select>
									<span class="help-block">{{ $errors->first('jenis_kelamin') }}</span>
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('tempat_lahir') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">tempat lahir</label>
									<input type="text" class="form-control" id="" placeholder="Tempat Lahir" name="tempat_lahir" value="{{ $errors->any() ? old('tempat_lahir') : $user->profil->tempat_lahir }}">
									<span class="help-block">{{ $errors->first('tempat_lahir') }}</span>										
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('tanggal_lahir') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Tanggal Lahir</label>
									<input type="date" class="form-control" name="tanggal_lahir" id="" placeholder="Tanggal Lahir" value="{{ $errors->any() ? old('tanggal_lahir') : $user->profil->tanggal_lahir }}">
									<span class="help-block">{{ $errors->first('tanggal_lahir') }}</span>																				
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('agama') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Agama</label>
									<select name="agama" id="" class="form-control">
										<option value="">Agama</option>
										<option value="islam" {{ $errors->any() ? (old('agama') == "islam" ? "selected" : "") : ($user->profil->agama == "islam" ? "selected" : "") }}>islam</option>
										<option value="kristen" {{ $errors->any() ? (old('agama') == "kristen" ? "selected" : "") : ($user->profil->agama == "kristen" ? "selected" : "") }}>kristen</option>
										<option value="budha" {{ $errors->any() ? (old('agama') == "budha" ? "selected" : "") : ($user->profil->agama == "budha" ? "selected" : "") }}>budha</option>
										<option value="hindu" {{ $errors->any() ? (old('agama') == "hindu" ? "selected" : "") : ($user->profil->agama == "hindu" ? "selected" : "") }}>hindu</option>
									</select>
									<span class="help-block">{{ $errors->first('agama') }}</span>																				
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('telepon') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Telepon</label>
									<input type="text" class="form-control" id="" placeholder="Telepon" name="telepon" value="{{ $errors->any() ? old('telepon') : $user->profil->telepon }}">
									<span class="help-block">{{ $errors->first('telepon') }}</span>																												
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('alamat') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">alamat</label>
									<textarea name="alamat" id="" cols="30" rows="10" placeholder="alamat" class="form-control">{{ $errors->any() ? old('alamat') : $user->profil->alamat }}</textarea>
									<span class="help-block">{{ $errors->first('alamat') }}</span>																												
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('role_id') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Role</label>
									<select name="role_id" id="" placeholder="Role" class="form-control">
										<option value="">Role</option>
										@foreach($roles as $role)
									<option value="{{ $role->id }}" {{ $errors->any() ? ($role->id == old('role_id') ? 'selected' : '') : ($user->role_id == $role->id ? "selected" : "") }}>{{ $role->role }}</option>
										@endforeach
									</select>
									<span class="help-block">{{ $errors->first('role_id') }}</span>																				
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('email') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Email</label>
									<input type="email" class="form-control" id="" placeholder="Email" name="email" value="{{ $errors->any() ? old('email') : $user->email }}">
									<span class="help-block">{{ $errors->first('email') }}</span>																												
								</div>

								@if($errors->any())
									<div class="form-group {{ $errors->has('foto') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Foto</label>
									<input type="file" class="form-control" id="" placeholder="Foto" name="foto">
									<span class="help-block">{{ $errors->first('foto') }}</span>																												
								</div>
							</div>
							<!-- /.box-body -->

							<div class="box-footer">
							<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- /.row -->
		</section>
		<!-- /.content -->
	</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('title','User')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                User
                <small>admin akademik</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <a href="{{ route('user.create') }}"><button class="btn btn-primary"><i class="fa fa-plus"></i> tambah data</button></a>
                        </div>

                        <!-- /.box-header -->
                        <div class="box-body">
                            @include('admin._partial.flash_message')
                            
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Nama Lengkap</th>
                                        <th>Jenis Kelamin</th>
                                        <th>telepon</th>
                                        <th>Email</th>
                                        <th>Level</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($users as $user)
                                        <tr>
                                            <td>{{ $user->nama_lengkap }}</td>
                                            <td>{{ $user->profil->jenis_kelamin }}</td>
                                            <td>{{ $user->profil->telepon }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>
                                                @if($user->role->id == 1)
                                                    <span for="" class="label label-success">{{ $user->role->role }}</span >
                                                @elseif($user->role->id == 2)
                                                    <span  for="" class="label label-info">{{ $user->role->role }}</span>
                                                @else
                                                    <span for="" class="label label-primary">{{ $user->role->role }}</span>
                                                @endif
                                            </td>
                                            <td>
                                                <a data-toggle="tooltip" data-placement="bottom" title="detail" href="{{ route('user.show',$user->id) }}"><button class="btn btn-sm btn-info"><i class="fa fa-th"></i></button></a>
                                                <a data-toggle="tooltip" data-placement="bottom" title="edit" href="{{ route('user.edit',$user->id) }}"><button class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></button></a>
                                                <form action="{{ route('user.destroy',$user->id) }}" style="display:inline-block;" method="POST" id="deleData_{{ $user->id }}">
                                                    @csrf
                                                    {{ method_field('DELETE') }}
                                                    <button data-toggle="tooltip" data-placement="bottom" title="delete" class="btn btn-danger btn-sm delete" id="{{ $user->id }}"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script src="{{ asset('assets/dist/js/sweetalert.min.js') }}"></script>
    <script>
    $(function () {
        $('#example1').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": false,
            "info": true,
            "autoWidth": false
        });

        $(document).on('click','.delete',function(e){
            e.preventDefault();
            var idForm = $(this).attr('id');
            swal({
                title: "Apakah anda yakin akan menghapus data user ?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                $('#deleteData_'+idForm).submit();
                swal("Data Terhapus", {
                    icon: "success", 
                });
                } else {
                swal("Data Masih Tersimpan"); 
                }
            });
        });
    });
    </script>
@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layouts.app')

@section('title','Detail User')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                User
                <small>admin akademik</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <a href="{{ route('user.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Nama Lengkap</th>
                                        <td>{{ $user->nama_lengkap }}</td>
                                    </tr>
                                     <tr>
                                        <th>Nomor Induk</th>
                                        <td>{{ $user->nomor_induk }}</td>
                                    </tr>
                                    <tr>
                                        <th>Jenis Kelamin</th>
                                        <td>{{ $user->profil->jenis_kelamin }}</td>
                                    </tr>
                                    <tr>
                                        <th>Tempat Lahir</th>
                                        <td>{{ $user->profil->tempat_lahir }}</td>
                                    </tr>
                                    <tr>
                                        <th>Tanggal Lahir</th>
                                        <td>{{ $user->profil->tanggal_lahir }}</td>
                                    </tr>
                                    <tr>
                                        <th>Agama</th>
                                        <td>{{ $user->profil->agama }}</td>
                                    </tr>
                                    <tr>
                                        <th>Telepon</th>
                                        <td>{{ $user->profil->telepon }}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{ $user->email }}</td>
                                    </tr>
                                    <tr>
                                        <th>Alamat</th>
                                        <td>{{ $user->profil->alamat }}</td>
                                    </tr>
                                    <tr>
                                        <th>Foto</th>
                                        <td>
                                        <img src="{{ asset('storage/profil/'.$user->profil->foto) }}" alt="" width="200px">
                                        </td>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection