routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear',function(){
  \Artisan::call('config:cache');
return "ada";
});


Route::group(['middleware' => 'auth'],function() {
    Route::get('','DashboardController@index')->name('dashboard')->middleware('kaprodi.auth');

    Route::resource('user','UserController')->middleware('kaprodi.auth');

    Route::resource('fakultas','FakultasController',['parameters' => [
        'fakultas'  => 'fakultas'
    ]])->except(['show'])->middleware('kaprodi.auth');

    Route::resource('prodi','ProdiController')->except(['show'])->middleware('kaprodi.auth');

    Route::resource('kelas','KelasController',['parameters' => [
        'kelas' => 'kelas'
    ]])->except(['show'])->middleware('kaprodi.auth');

    Route::resource('matakuliah','MatakuliahController')->middleware('kaprodi.auth');
    Route::resource('tahun-ajaran','TahunAjaranController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('kurikulum','KurikulumController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('jenis-ujian','JenisUjianController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('jadwal-ujian','JadwalUjianController')->except(['show'])->middleware('kaprodi.auth');
    Route::resource('arsip-soal','ArsipSoalController')->except(['edit','update']);
    Route::resource('arsip-nilai','ArsipNilaiController')->except(['edit','update']);

    // export pdf
    Route::get('arsip-soal/pdf/{id}','ArsipSoalController@exportPdf')->name('arsip_soal.pdf');
    Route::get('arsip-nilai/pdf/{id}','ArsipNilaiController@exportPdf')->name('arsip_nilai.pdf');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/JenisUjian.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JenisUjian extends Model
{
    protected $table = 'jenis_ujian';

    protected $fillable = [
        'kode_jenis_ujian',
        'jenis_ujian'
    ];

    public function jadwalUjian()
    {
        return $this->hasMany('App\JadwalUjian','id_jenis_ujian','id');
    }

    public function arsipSoal()
    {
        return $this->hasMany('App\ArsipSoal','id_jenis_ujian','id');
    }

     public function arsipNilai()
    {
        return $this->hasMany('App\ArsipNilai','id_jenis_ujian','id');
    }
}

app/Http/Controllers/JenisUjianController.php
<?php

namespace App\Http\Controllers;

use App\JenisUjian;
use App\Http\Requests\JenisUjianRequest;
use Illuminate\Http\Request;

class JenisUjianController extends Controller
{

    public function index()
    {
        $dataJenisUjian = JenisUjian::orderBy('id','DESC')->get();
        return view('admin.jenis_ujian.index',compact('dataJenisUjian'));
    }

    public function create()
    {
        return view('admin.jenis_ujian.create');
    }

    public function store(JenisUjianRequest $request)
    {
        JenisUjian::create($request->all());
        return redirect()->route('jenis-ujian.index')->with('flash_message','tambah data jenis ujian berhasil');
    }

    public function edit(JenisUjian $jenisUjian)
    {
        return view('admin.jenis_ujian.edit',compact('jenisUjian'));
    }

    public function update(JenisUjianRequest $request, JenisUjian $jenisUjian)
    {
        $jenisUjian->update($request->all());
        return redirect()->route('jenis-ujian.index')->with('flash_message','update data jenis ujian berhasil');
    }

    public function destroy(JenisUjian $jenisUjian)
    {
        $jenisUjian->delete();
        return redirect()->route('jenis-ujian.index')->with('flash_message','hapus data jenis ujian berhasil');
    }
}

resources/views/admin/jenis_ujian/create.blade.php
@extends('admin.layouts.app')

@section('title','Tambah Jenis Ujian')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Tambah Jenis Ujian
				<small>Admin Akademik</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Forms</a></li>
				<li class="active">General Elements</li>
			</ol>
		</section>

		<!-- Main content -->
		<section class="content">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="box box-primary">
						<div class="box-header with-border">
							<a href="{{ route('jenis-ujian.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
						</div>
						<!-- form start -->
						<form method="POST" role="form" action="{{ route('jenis-ujian.store') }}">
							@csrf
							<div class="box-body">
								@if($errors->any())
									<div class="form-group {{ $errors->has('kode_jenis_ujian') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Kode Jenis Ujian</label>
									<input type="text" class="form-control" id="" placeholder="Kode Jenis Ujian" name="kode_jenis_ujian" value="{{ old('kode_jenis_ujian') }}">
									<span class="help-block">{{ $errors->first('kode_jenis_ujian') }}</span>
                                </div>
                                

								@if($errors->any())
									<div class="form-group {{ $errors->has('jenis_ujian') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Jenis Ujian</label>
									<select name="jenis_ujian" id="" class="form-control">
                                        <option value="">Jenis Ujian</option>
                                        <option value="UTS" {{ old('jenis_ujian') == "UTS" ? 'selected' : '' }}>UTS</option>
                                        <option value="UAS" {{ old('jenis_ujian') == "UAS" ? 'selected' : '' }}>UAS</option>
                                        <option value="Susulan" {{ old('jenis_ujian') == "Susulan" ? 'selected' : '' }}>Susulan</option>
                                    </select>
									<span class="help-block">{{ $errors->first('jenis_ujian') }}</span>										
                                </div>

							<div class="box-footer">
							<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- /.row -->
		</section>
		<!-- /.content -->
	</div>
@endsection

resources/views/admin/jenis_ujian/edit.blade.php
@extends('admin.layouts.app')

@section('title','Tambah Jenis Ujian')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Edit Jenis Ujian
				<small>Admin Akademik</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Forms</a></li>
				<li class="active">General Elements</li>
			</ol>
		</section>

		<!-- Main content -->
		<section class="content">
			<div class="row">
				<!-- left column -->
				<div class="col-md-12">
					<!-- general form elements -->
					<div class="box box-primary">
						<div class="box-header with-border">
							<a href="{{ route('jenis-ujian.index') }}"><button class="btn btn-success"><i class="fa fa-chevron-left"></i> Kembali</button></a>
						</div>
						<!-- form start -->
						<form method="POST" role="form" action="{{ route('jenis-ujian.update',$jenisUjian->id) }}">
                            @csrf
                            {{ method_field('PATCH') }}
                            <input type="hidden" name="id" value="{{ $jenisUjian->id }}">
							<div class="box-body">
								@if($errors->any())
									<div class="form-group {{ $errors->has('kode_jenis_ujian') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Kode Jenis Ujian</label>
									<input type="text" class="form-control" id="" placeholder="Kode Jenis Ujian" name="kode_jenis_ujian" value="{{ $errors->any() ? old('kode_jenis_ujian') : $jenisUjian->kode_jenis_ujian }}">
									<span class="help-block">{{ $errors->first('kode_jenis_ujian') }}</span>
                                </div>
                                
								@if($errors->any())
									<div class="form-group {{ $errors->has('jenis_ujian') ? 'has-error' : 'has-success' }}">
								@else
									<div class="form-group">
								@endif
									<label for="">Jenis Ujian</label>
									<select name="jenis_ujian" id="" class="form-control">
                                        <option value="">Jenis Ujian</option>
                                        <option value="UTS" {{ $errors->any() ? (old('jenis_ujian') == "UTS" ? 'selected' : '') : ($jenisUjian->jenis_ujian == "UTS" ? 'selected' : '') }}>UTS</option>
                                        <option value="UAS" {{ $errors->any() ? (old('jenis_ujian') == "UAS" ? 'selected' : '') : ($jenisUjian->jenis_ujian == "UAS" ? 'selected' : '') }}>UAS</option>
                                        <option value="Susulan" {{ $errors->any() ? (old('jenis_ujian') == "Susulan" ? 'selected' : '') : ($jenisUjian->jenis_ujian == "Susulan" ? 'selected' : '') }}>Susulan</option>
                                    </select>
									<span class="help-block">{{ $errors->first('jenis_ujian') }}</span>										
                                </div>

							<div class="box-footer">
							<button type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
			<!-- /.row -->
		</section>
		<!-- /.content -->
	</div>
@endsection

resources/views/admin/jenis_ujian/index.blade.php
@extends('admin.layouts.app')

@section('title','Jenis Ujian')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Jenis Ujian
                <small>admin akademik</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-header">
                            <a href="{{ route('jenis-ujian.create') }}"><button class="btn btn-primary"><i class="fa fa-plus"></i> tambah data</button></a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            @include('admin._partial.flash_message')
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Kode Jenis Ujian</th>
                                        <th>Jenis Ujian</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($dataJenisUjian as $jenisUjian)
                                        <tr>
                                            <td>{{ $jenisUjian->kode_jenis_ujian }}</td>
                                            <td>{{ $jenisUjian->jenis_ujian }}</td>
                                            <td>
                                                <a data-toggle="tooltip" data-placement="bottom" title="edit" href="{{ route('jenis-ujian.edit',$jenisUjian->id) }}"><button class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></button></a>
                                                <form action="{{ route('jenis-ujian.destroy',$jenisUjian->id) }}" style="display:inline-block;" method="POST" id="deleteData_{{ $jenisUjian->id }}">
                                                    @csrf
                                                    {{ method_field('DELETE') }}
                                                    <button data-toggle="tooltip" data-placement="bottom" title="delete" class="btn btn-danger btn-sm delete" id="{{ $jenisUjian->id }}"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('script')
    <script src="{{ asset('assets/dist/js/sweetalert.min.js') }}"></script>
    <script>
    $(function () {
        $('#example1').DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": false,
            "info": true,
            "autoWidth": false
        });

        $(document).on('click','.delete',function(e){
            e.preventDefault();
            var idForm = $(this).attr('id');
            swal({
                title: "Apakah anda yakin akan menghapus data tahun ajaran ?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                $('#deleteData_'+idForm).submit();
                swal("Data Terhapus", {
                    icon: "success", 
                });
                } else {
                swal("Data Masih Tersimpan"); 
                }
            });
        });
    });
    </script>
@endsection